language: julia

os:
  - linux

julia:
  - 1.1
  
before_install:
  - julia -e 'using Pkg; Pkg.clone("https://github.com/amontoison/Cxx.jl.git"); Pkg.build("Cxx")'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
